version="2"

bindaddress = "[::]:8443"
ldapbindaddress = "[::]:3636"

db_path = "/data/kanidm.db"
# db_fs_type = "zfs"

tls_chain = "/config/certs/chain.pem"
tls_key = "/config/certs/key.pem"

# log_level = "debug"

domain = "auth.magisystem.xyz"
origin = "https://auth.magisystem.xyz"

[online_backup]
path = "/data/kanidm/backups/"
schedule = "00 00 * * *"
