---
services:
  navidrome:
    image: deluan/navidrome:latest
    restart: unless-stopped
    environment:
      ND_SESSIONTIMEOUT: 24h
      ND_TRANSCODINGCACHESIZE: 5 GiB
      #ND_ENABLETRANSCODINGCONFIG: 'true'
      ND_ENABLESHARING: 'true'
      ND_REVERSEPROXYWHITELIST: '{{ reverse_proxy_network_subnet }}'
      ND_REVERSEPROXYUSERHEADER: X-authentik-username
      ND_SUBSONICARTISTPARTICIPATIONS: 'true'
      ND_LASTFM_ENABLED: 'true'
      ND_LASTFM_APIKEY: '{{ navidrome_lastfm_apikey }}'
      ND_LASTFM_SECRET: '{{ navidrome_lastfm_secret }}'
      ND_SPOTIFY_ID: '{{ navidrome_spotify_clientid }}'
      ND_SPOTIFY_SECRET: '{{ navidrome_spotify_secret }}'
      ND_LOGLEVEL: debug
    networks:
      - outside
      - reverse-proxy-network
    volumes:
      - '{{ (navidrome_data_folder, "navidrome") | path_join }}:/data'
      - '{{ navidrome_music_folder }}:/music:ro'
    labels:
      traefik.enable: 'true'
      traefik.http.routers.navidrome.rule: Host(`music.magisystem.xyz`)
      traefik.http.routers.navidrome.middlewares: navidrome-auth
      traefik.http.routers.navidrome.service: navidrome
      traefik.http.routers.navidrome-api-no-auth.rule: Host(`music.magisystem.xyz`) && (PathPrefix(`/rest`) || PathPrefix(`/share`))
      traefik.http.routers.navidrome-api-no-auth.service: navidrome
      traefik.http.routers.navidrome-auth.rule: Host(`music.magisystem.xyz`) && PathPrefix(`/outpost.goauthentik.io/`)
      traefik.http.routers.navidrome-auth.service: 'authentik@{{ authentik_provider }}'
      traefik.http.middlewares.navidrome-auth.forwardauth.address: https://music.magisystem.xyz/outpost.goauthentik.io/auth/traefik
      traefik.http.middlewares.navidrome-auth.forwardauth.trustForwardHeader: 'true'
      traefik.http.middlewares.navidrome-auth.forwardauth.authResponseHeaders: X-authentik-username
      traefik.http.services.navidrome.loadbalancer.server.port: '4533'

  slskd:
    image: slskd/slskd:latest
    restart: unless-stopped
    user: 1000:1000
    environment:
      SLSKD_SHARED_DIR: /music
      SLSKD_DOWNLOADS_DIR: /downloads
      SLSKD_SLSK_USERNAME: '{{ navidrome_slsk_username }}'
      SLSKD_SLSK_PASSWORD: '{{ navidrome_slsk_password }}'
      SLSKD_NO_AUTH: true
      SLSKD_INSTANCE_NAME: '{{ inventory_hostname }}'
      SLSKD_UPLOAD_SPEED_LIMIT: {{ 1 * 1024 * 1024 }}
      SLSKD_DOWNLOAD_SPEED_LIMIT: {{ 1 * 1024 * 1024 }}
    networks:
      - outside
      - reverse-proxy-network
    ports:
      - 50300:50300
    volumes:
      - '{{ (navidrome_data_folder, "slskd") | path_join }}:/app'
      - '{{ navidrome_music_ingest_folder }}:/downloads'
      - '{{ navidrome_music_folder }}:/music:ro'
    labels:
      traefik.enable: 'true'
      traefik.http.routers.slskd.rule: Host(`music.slsk.magisystem.xyz`)
      traefik.http.routers.slskd.middlewares: slskd-auth
      traefik.http.routers.slskd-auth.rule: Host(`music.slsk.magisystem.xyz`) && PathPrefix(`/outpost.goauthentik.io/`)
      traefik.http.routers.slskd-auth.service: 'authentik@{{ authentik_provider }}'
      traefik.http.middlewares.slskd-auth.forwardauth.address: https://music.slsk.magisystem.xyz/outpost.goauthentik.io/auth/traefik
      traefik.http.middlewares.slskd-auth.forwardauth.trustForwardHeader: 'true'
      traefik.http.services.slskd.loadbalancer.server.port: 5030

  beets:
    image: lscr.io/linuxserver/beets:latest
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Rome
    networks:
      - outside
      - reverse-proxy-network
    volumes:
      - '{{ navidrome_music_ingest_folder }}:/downloads'
      - '{{ navidrome_music_folder }}:/music'
      - '{{ (navidrome_data_folder, "beets") | path_join }}:/config'
      - ./beets.yml:/config/config.yaml

networks:
  outside:
    internal: false
  reverse-proxy-network:
    name: reverse-proxy
    external: true
