providers:
  docker:
    network: reverse-proxy
    endpoint: "tcp://socket-proxy:2375"
    exposedByDefault: false
  file:
    directory: /etc/traefik/configs

api:
  dashboard: true

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
    asDefault: {{ 'http' is in traefik_default_entrypoints | ternary('true', 'false') }}

  https:
    address: ":443"
    http3: {}
    http:
      tls:
        certResolver: tls-resolver
    asDefault: {{ 'https' is in traefik_default_entrypoints | ternary('true', 'false') }}

  admin:
    address: ":8080"

certificatesResolvers:
  tls-resolver:
    acme:
      email: "{{ certificate_email }}"
#      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      tlsChallenge: {}

#log:
#  level: DEBUG
