---
services:
  redis:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - default

  database:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW --character-set-server=utf8
    restart: unless-stopped
    networks:
      - default
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 'yes'
      MARIADB_DATABASE: nextcloud
      MARIADB_USER: nextcloud
      MARIADB_PASSWORD: '{{ nextcloud_database_password }}'
    volumes:
      - '{{ (nextcloud_data_folder, "data") | path_join }}:/var/lib/mysql'
      - /etc/localtime:/etc/localtime:ro

  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    restart: unless-stopped
    depends_on:
      - redis
      - database
    networks:
      - default
      - outside
      - reverse-proxy-network
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Rome
      DOCKER_MODS: linuxserver/mods:universal-stdout-logs
      LOGS_TO_STDOUT: /data/nextcloud.log
    volumes:
      - '{{ (nextcloud_data_folder, "app-config") | path_join }}:/config'
      - '{{ (nextcloud_data_folder, "app-data") | path_join }}:/data'
    labels:
      com.centurylinklabs.watchtower.monitor-only: 'true'
      traefik.enable: 'true'
      traefik.http.routers.nextcloud.rule: Host(`cloud.magisystem.xyz`)
      traefik.http.routers.nextcloud.middlewares: nextcloud-header
      traefik.http.middlewares.nextcloud-header.headers.stsSeconds: 15552000
      traefik.http.services.nextcloud.loadbalancer.server.scheme: https
      traefik.http.services.nextcloud.loadbalancer.server.port: 443
      traefik.http.services.nextcloud.loadbalancer.serversTransport: nextcloud_transport@file

  collabora:
    image: collabora/code
    restart: unless-stopped
    networks:
      - outside
      - reverse-proxy-network
    environment:
      TZ: Europe/Rome
      DONT_GEN_SSL_CERT: yes
      aliasgroup1: https://cloud.magisystem.xyz:443
      extra_params: >
        --o:ssl.enable=false --o:ssl.termination=true --o:admin_console.enable=false
    labels:
      com.centurylinklabs.watchtower.monitor-only: 'true'
      traefik.enable: 'true'
      traefik.http.routers.collabora.rule: Host(`office.magisystem.xyz`) && !PathPrefix(`/cool/getMetrics`)
      traefik.http.services.collabora.loadbalancer.server.port: 9980

networks:
  default:
    internal: true
  outside:
    internal: false
  reverse-proxy-network:
    name: reverse-proxy
    external: true
