http:
  tls: false

auth_middleware:
  # credentials_by_user_agent: {}
  allow_app_auth: true

auto_provision_accounts: true
csp_config_file_location: '/etc/opencloud/csp.yaml'

auto_provision_claims:
  username: preferred_username
  email: email
  display_name: name
  groups: opencloud_groups
user_oidc_claim: preferred_username

role_assignment:
  driver: oidc
  oidc_role_mapper:
    role_claim: role
    role_mapping:
      - role_name: admin
        claim_value: admin
      - role_name: spaceadmin
        claim_value: spaceadmin
      - role_name: user
        claim_value: user
      - role_name: guest
        claim_value: guest

role_quotas:
  admin: 0
  spaceadmin: 0
  user: 10737418240
  guest: 0
