- become: true
  block:
    - name: Add network repo from Open Build Service
      community.general.zypper_repository:
        auto_import_keys: false
        repo: 'https://download.opensuse.org/repositories/network/openSUSE_Tumbleweed/network.repo'

    - name: Install packages
      community.general.zypper:
        name:
          - docker
          - docker-compose
          - ddclient
          - python311-requests

    - name: Make Docker remap users by default
      ansible.builtin.lineinfile:
        path: /etc/sysconfig/docker
        search_string: 'DOCKER_OPTS="'
        line: 'DOCKER_OPTS="--userns-remap default --default-address-pool base=172.17.0.0/12,size=24"'
      register: ayanami_setup_sysconfig_docker

    - name: Start and enable docker
      ansible.builtin.systemd_service:
        name: docker.service
        enabled: true
        state: '{{ (ayanami_setup_sysconfig_docker is changed) | ternary("reloaded", "started") }}'

#   - name: Configure ddclient
#     ansible.builtin.blockinfile:
#       path: /etc/ddclient.conf
#       block: |
#         use=web
#         protocol=hetzner
#         password={{ ddclient_hetzner_token }}
#         zone=magisystem.xyz
#         music.magisystem.xyz,music.slsk.magisystem.xyz
#     register: ayanami_setup_ddclient

#   - name: Start and enable ddclient
#     ansible.builtin.systemd_service:
#       name: ddclient.service
#       enabled: true
#       state: '{{ (ayanami_setup_ddclient is changed) | ternary("restarted", "started") }}'
